# Generated by Django 5.1 on 2024-08-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0007_alter_author_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
