# Generated by Django 5.1 on 2024-08-29 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0009_author_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
