# Generated by Django 5.1 on 2024-09-05 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_answer_is_correct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_text',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
    ]
